port: 80
contentPath: ./content
https:
  enabled: true
  port: 443
  certificate:
    path: ./certs/server.pfx
    pass: thisisastrongpasswordyo
    pem:
      usePem: true
      certPath: ./certs/domain.cert.pem
      keyPath: ./certs/private.key.pem
      keyPass: ""
